Add devise
yin-ka/blog-app pull request #9
Opened 2023-10-12 11:18 UTC by yin-ka

In this PR, I:

- Remove current_user method in ApplicationController, devise will provide us with one.
- Installed and setup devise.
- Set up app to register a new user.
- Set up user logs in with a combination of email and password.
- Hashed password should be stored in the database.
- Set up confirmation of email.
- Set up reset password functionality.
- Modify the views in devise.
- Restyled the app.

2023-10-12 12:06 UTC, NahnahAJ requested changes
## Project Status: CHANGES REQUIRED :recycle: 
Hi @yin-ka , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media2.giphy.com/media/WGpR51t9qb79SNFOts/giphy.gif"/>

## Highlights :fire: 
- The current_user method in ApplicationController has been removed :heavy_check_mark: 
- `Devise` has been installed and setup properly :heavy_check_mark: 
- The application allows for registering a new user :heavy_check_mark: 
- A user can log in with a combination of email and password :heavy_check_mark: 
- A hashed password is stored in the database  :heavy_check_mark:

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-12 12:06 UTC, nahnahdev commented on db/migrate/20230930151652_create_users.rb
> +
- [ ] Great job with your Project @yin-ka Everything looks great. However, when I cloned your project and tried to run it, I was faced with a couple of errors and that was because you have included this `confirmable` here and in another migration file as well. As a result, there were duplicates. :thinking: 
- [ ] So kindly remove this from user `user migration file` and delete this migration file `20231012110626_add_confirmable_to_devise` from your project so your app will only make use of the one in the `devise.rb` migration file when creating the tables that way preventing errors :wink: 
- [ ] After that the next reviewer can check and ensure that the views in devise for the `registration` and `login` have been modified to match the wireframes and their styling :wink: 
- You can take a look at the wireframes in the [sneak peek](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/sneak_peek.md) of the project.

- Error Message
![image](https://github.com/yin-ka/blog-app/assets/102699958/c1916922-adfb-4bb8-99f9-a2ce098e4041)

2023-10-12 12:10 UTC, yin-ka commented on db/migrate/20230930151652_create_users.rb
> +
Okay, thanks @NahnahAJ for the review. I will make the required adjustments.

2023-10-12 13:09 UTC, codepantha requested changes
# STATUS: CHANGES REQUIRED ♻️ 

## Hi team 👋, 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media0.giphy.com/media/rZ10JtoPRv1Ly/giphy.gif"/>

## Highlights 🎯 
✔️The current_user method in `ApplicationController` has been removed 📌 
✔️ User authentication implemented with `Devise` 📌 
✔️ No linter errors 🟢 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-12 13:09 UTC, codepantha commented on app/views/devise/registrations/new.html.erb
> +  </div>
- [ ] Please style the submit button in accordance to the wireframe design as you can see below 👇 
### Wireframe Design
![image](https://github.com/yin-ka/blog-app/assets/46839548/1c08f055-1ef6-4a6b-8846-8ab45c3d09a6)

### Your Design
![image](https://github.com/yin-ka/blog-app/assets/46839548/055b19c7-78ef-4185-968b-3c5f81f304d4)

- [x] Please do the same for the login page 👍

2023-10-13 00:50 UTC, yin-ka commented on app/views/devise/registrations/new.html.erb
> +  </div>
Thanks for the feedback. @codepantha. Will make the required changes.

2023-10-13 01:10 UTC, KanzaTahreem approved these changes
# Approved 🙌

Hi @yin-ka 

Good job implementing the suggested changes💪 **_Your project is COMPLETE! There is nothing else to say other than... it's time to merge it! 🚀 Congratulations!_**

<img src="https://media.tenor.com/xDHCe07zrocAAAAC/congrats-minions.gif"/>

## Highlights 🎯
There are some excellent points that you have made perfectly. Keep up the great work! 👏

-  ✅ Styling is looking great
-  ✅ Implemented suggestions
-  ✅ Your README looks good
-  ✅ Linters are working properly

## Optional suggestions ❕
N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-13 07:24 UTC, merged